### ISSUE TITLE
ColResize: strange visual effect in chrome

### ISSUE THREAD

**Issue by rockshandy** [maca88/datatables.plugins#20]
First I'd like to say awesome plugin for the newer version of DataTables! I've been experimenting with column resizing with scrollX set which seems to work fine in Firefox. When I resize columns in chrome, some of the column content (and headers) are a little glitchy.

Sometimes half the cell (dived horizontally) will move or header text will disappear. It does correct itself once I move my mouse over the strange looking area, updating to what would expect. This doesn't seem to happen if disable horizontal scrolling.

Here are my initial options to DataTables:
```javascript
{
  deferRender: true,
  scrollX: true,
  dom: 'lrtpRJ',
  colResize: {
    fixedLayout: true,
    minWidth: 40
  }
}
```
I also have some basic css for overflow:
```css
table.dataTable td, table.dataTable th {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```
Have you seen this happen before?
