### ISSUE TITLE
Problem with ColResize

### ISSUE THREAD

**Issue by ghost** [maca88/datatables.plugins#24]
Good day!

First off, thanks for an incredibly helpful tool and plugins! 

I'm having a problem with getting the functionality of ColResize to work. It initiates well (I believe) as the drag mouse pointer appears when hovering over the edges over each column but clicking on them does absolutely nothing. (it also buggers the alignment of the Columns, but that is a minor problem, not really important).

I am just wondering what components or settings in my CSS or what not that could create this kind of problem. :) I am fairly new to JS and CSS in general. 

Any help is sincerely appreciated.

**Comment by maca88** [comment]
Hello,

when the drag mouse pointer appears you need to click and then drag left or right to resize the column.
Simple example [HERE](http://live.datatables.net/IroN/279/).

As you can see in the above example you just need the following css:

``` css
table.dataTable td, table.dataTable th {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```
